### ISSUE TITLE
It should be possible to inform target host from env too

### ISSUE THREAD

**Issue by xinitrc86** [lemaiwo/ui5-middleware-route-proxy#4]
Hello, 
Currently only user and password are being retrieved from ENV. The target host should too, without this, its complicate to integrate the plugin in a CI/CD pipeline.

I.e from:
```
      sap: 
        target: **https://cdi2dbldapp11.bold.d1.ad.local:8200**
        auth:
          fromEnv: true
          user: UI5_TASK_NWABAP_DEPLOYER__USER
```

I.e to:
```
      sap: 
        target: UI5_TASK_NWABAP_DEPLOYER__SERVER
        auth:
          fromEnv: true
          user: UI5_TASK_NWABAP_DEPLOYER__USER
```

Regards,
Felipe Silva
